title: HTMLyrics
iconURL: assets/default-icon.png
theme: jekyll-theme-htmlyrics

# for a clean URL
permalink: :slug

paginate: 5
paginate_path: "/blog/page:num/"

social:
  twitter: #url
  github: #url

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 3466
google_analytics: UA-NNNNNNNN-N
